### ISSUE TITLE
Can't connect to WiFi with space in name

### ISSUE THREAD

**Issue by qwasy** [michaelshmitty/esperpass#4]
My WiFi has a space character in the name, and the nodemcu can't connect to it.
Log says "disconnect from ssid [first part of WiFi name], reason 201"
I also tried putting the name in "" but that doesn't work either.

**Comment by michaelshmitty** [comment]
Good find.
There's no easy fix for this because the space character is used as a parameter separation character in the command parser.
So a command like "set ssid network_name" is split into tokens separated by the space character.
If I have time to figure out a safe way to fix this, I will.
Here's the function that parses the string into tokens:
https://github.com/michaelshmitty/esperpass/blob/master/user/user_main.c#L204
And here is the code that handles setting the ssid:
https://github.com/michaelshmitty/esperpass/blob/master/user/user_main.c#L811

For what it's worth this looks like it's a bug/limitation in the [WiFi Repeater firmware](https://github.com/martin-ger/esp_wifi_repeater) that this project is based on as well.

**Comment by michaelshmitty** [comment]
Compiling is easy once you've set it up. It's a cross-compile toolchain for ESP8266 chips. The only trouble is that it needs a case sensitive filesystem, which Windows is unable to provide.
So you have to set up a build environment on Linux or MacOS (which is what I use).

Here's what I can do: if you give me the name of your wireless network (without the password of course) I'll recompile a version for you that has the default settings configured for your wifi network. You can then flash that version to your ESP8266 chip and all you need to do is configure the wifi password and you're set. Let me know if you'd like that and then let me know the name of the wifi network.

**Comment by BenKesselring** [comment]
Would it be possible to set an escape character (like backslash in the *nix command line) for the "set ssid" function? I think most people would be fine adding a backslash to their WiFi SSID in the config file if they understood why they needed to.

**Comment by michaelshmitty** [comment]
This is now fixed in version 0.0.3. Spaces are now allowed in the ssid as well as the password.
