### ISSUE TITLE
Not sure if working..

### ISSUE THREAD

**Issue by qwasy** [michaelshmitty/esperpass#5]
I got the WiFi Part working, thanks^^
But I'm not sure, if the streetpass is working. 
It run for about an hour, and no new mii was found...

This is the Log:
`
Config found and loaded
mode : sta(5c:cf:7f:53:be:6d) + softAP(4e:53:50:4f:4f:40)
add if0
add if1
dhcp server start:(ip:192.168.4.1,mask:255.255.255.0,gw:192.168.4.1)
bcn 100
scandone
state: 0 -> 2 (b0)
state: 2 -> 3 (0)
state: 3 -> 5 (10)
add 0
aid 6
cnt

connected with Zombiepotato Holocaust, channel 5
dhcp client start...
connect to ssid Zombiepotato Holocaust, channel 5
ip:192.168.1.173,mask:255.255.255.0,gw:192.168.1.1
ip:192.168.1.173,mask:255.255.255.0,gw:192.168.1.1,dns:192.168.1.1
add 1
aid 1
station: 40:f4:07:36:49:ed join, AID = 1
station: 40:f4:07:36:49:ed join, AID = 1
station: 40:f4:07:36:49:ed leave, AID = 1
rm 1
station: 40:f4:07:36:49:ed leave, AID = 1
add 1
aid 1
station: 40:f4:07:36:49:ed join, AID = 1
station: 40:f4:07:36:49:ed join, AID = 1
station: 40:f4:07:36:49:ed leave, AID = 1
rm 1
station: 40:f4:07:36:49:ed leave, AID = 1
add 1
aid 1
station: 40:f4:07:36:49:ed join, AID = 1
station: 40:f4:07:36:49:ed join, AID = 1
station: 40:f4:07:36:49:ed leave, AID = 1
rm 1
station: 40:f4:07:36:49:ed leave, AID = 1
`

**Comment by michaelshmitty** [comment]
Which version are you currently using? You can see this by issuing the "show" command at the CMD> prompt. Don't copy paste everything it puts out as it contains your WiFi password. Just the version will do.

I am now testing the version 0.0.4 which has support for the spaces in the ssid and password and I notice I'm not getting any streetpasses either. I will test a while longer until I'm convinced I introduced a problem since version 0.0.1.
Connectivity seems to work because when you issue a "acl from_sta clear" (which will remove all firewall rules) and you connect to the "attwifi" network, you can surf anywhere through the chip.
When you do this keep in mind to issue a "reset factory" and reconfigure Esperpass afterwards because flushing the firewall rules will be stored in the config and you don't want to manually enter all the rules again.

So I hope my fix for allowing spaces in the ssid and password didn't break things. I don't immediately see how it could but you never know for sure with this embedded devices system programming. It's C after all so it's fairly easy to write garbage somewhere which may cause the thing to stop working. I have not found a way to run the code through a debugger, so that doesn't help either.

I'll report back to this issue after I've left it running overnight. It's bound to cycle through a bunch of MAC addresses (one per hour) so there should hopefully be some tags during that time.

**Comment by qwasy** [comment]
It's Version V0.0.3 (build: Tue Mar 13 15:44:35 2018)
Okay, I'll wait^^

Maybe you could use a random Mac address from the list on every boot/reboot?
Maybe the Mac is the Problem, and not your Code^^
Also, but I'm unsure about the current state, but I think the 3DS only connects every 8 hour to one of the Mac, so if it was already connected, you wouldn't notice for the next few hours...
And last, in the output it would be nice to see if a 3DS, or more, are connected^^

**Comment by michaelshmitty** [comment]
Cool, in the mean time version 0.0.4 is out. Just a very small fix that should not have any major effect on anything so 0.0.3 should work too.
I will start figuring out how to use GitHub releases so I can keep the binaries for earlier versions online. This way if I break something in a new version, you can still go back to the previous binary version without having to set up a build env en recompile yourself.

Yes a random mac on boot would be cool. I'll see if I have time to implement that. I'm also not sure about this list of mac addresses I currently have in there. To be honest I'm not 100% clear on how these lists of macs work on http://homepass.info/ There are mac address apart from the official ones, I'm not sure what's up with those. It would be nice if it were possible to manage the list of mac addresses through the command line, but that's quite a big feature to implement and I'm not an expert C programmer yet to do this well.

You are right, the 3DS only connects to the same mac address every 8 hours. That's why I have currently set the rotation period to 1 hour. There are at the moment about [16 mac addresses in the list](https://github.com/michaelshmitty/esperpass/blob/master/user/config_flash.c#L60). So in about 16 hours esperpass should rotate through the entire list. I hope at least one of those will trigger some tags so I know version 0.0.4 is working. Otherwise I have to revert back to version 0.0.2 and it's back to the drawing board!

In the output you should be able to confirm that your 3DS has connected because it keeps a list of DHCP leases. I believe the command is "show stats" at the CMD> command line. I have seen my 3DS and my computer in that list.
You should also check if you can connect to the "attwifi" network with your PC and get an IP address.
As per my previous comment if you then clear the acl (firewall) rules, you should be able to surf the web normally and that should confirm that at least the wifi bridge part works.
Not getting tags could be caused by a problem with the mac address introduced by a bug somewhere in version 0.0.3 or 0.0.4 or it could be that there is a temporary problem with Streetpass connectivity for all we know.

I'll keep an eye on my 3DS and update this issue with more news. Good luck!

**Comment by michaelshmitty** [comment]
I've gone ahead and created some releases that include the binaries for each version. If it turns out that the support for space characters in the ssid and the password has broken things completely then it's easy for others to download [version 0.0.2](https://github.com/michaelshmitty/esperpass/releases/download/v0.0.2/esperpass-firmware-v0.0.2.zip) which was known to be working and use that one until it's confirmed that version 0.0.4 works as expected.

**Comment by michaelshmitty** [comment]
Hmm not a single tag in over 16 hours. Something's definitely wrong here. It's likely that adding support for the space character in the ssid and password has broken something else. It's not the bridge functionality because I'm posting this message through the "attwifi" ssid with all acl's cleared.
I see the MAC address rotate every hour so that still seems to work. Very strange. I'll look into this later.
Until then I recommend everyone to use the [v0.0.2 release](https://github.com/michaelshmitty/esperpass/releases/tag/v0.0.2) which does not support a space character in the ssid and password until this is sorted out.

**Comment by michaelshmitty** [comment]
Hmmmmm, something weird is going on. I went to the office today where I have an esperpass version 0.0.2 still running and I'm not getting any streetpass tags there either. So this may have nothing to do with the latest updates to allow spaces. It's either another problem or there is an external factor that's causing problems with streetpass.
I find it very suspect that I've had a bunch of tags daily in the office the past couple of days and now suddenly no more tags. I've restarted the ESP8266 just in case but still no tags. Everything seems to work fine though, connectivity is ok. To be continued...

**Comment by michaelshmitty** [comment]
So I reverted back to version 0.0.2 and I still don't get tags that often. So I'm still not convinced I've introduced an error with the space character support. What I think could be happening is one of the following:

- The Nintendo cooldown period for a single mac address is for some reason longer than 8 hours. Or perhaps the system has throttled my because of the amount of tags I've received in the last week.
- There are other IP addresses for Streepass that my 3DS is trying to connect to but that are not allowed by the firewall rules. I took the list of IP addresses from the RaspiPass source code, but I am not sure how accurate / up to date that list is. I will test this in the next couple of days by disabling the firewall on my esperpass on the latest firmware (0.0.4). If I notice an increase in tags I will set up some sort of monitoring system to extract the Streetpass relay IP addresses that are not in the acl list yet.
- Some of the mac addresses in the currently hardcoded list in esperpass are not supported anymore and that may cause the reduction in tags. I took these from the list at (homepass.info](http://homepass.info) but there are a lot more mac addresses there that I didn't include for this early test version. I will also try to experiment with those.

Currently not flagging this as a bug as I don't see any improvements with going back to an earlier version. More later...

**Comment by Dal78** [comment]
Easiest test might be bringing a pi based solution up and seeing if the relay network is down.  Nintendo pushed out firmware 5.0 on the switch today so its plausible they made other changes.

**Comment by michaelshmitty** [comment]
Ok so I'm getting tags now with the latest version 0.0.5 but with the firewall rules disabled. It's possible there are more relay Streetpass IP addresses [than configured in this list](https://github.com/michaelshmitty/esperpass/blob/master/user/config_flash.c#L94).

So I'm going to assume this issue is in fact not an issue with the space character support that was added and likely caused by overzealous firewall rules that allow only a subset of Streetpass IP addresses, a limited mac address list, issues with the Streetpass network at NIntendo's side, a longer cooldown period than documented or just no available tags on the servers queried during these tests. Let's see how it progresses when more people try it out.

For reference if you want to disable the built-in firewall rules for testing purposes, issue the following commands:
```
CMD> acl from_sta clear
CMD> save
CMD> reset
```
You can then also verify that your esperpass works by connecting to the "attwifi" network and trying to browse the Internet. Keep in mind that this does expose your unrestricted Internet connection to anyone passing by and connecting to the insecure "attwifi" network. So test at your own risk! If you want to restore the built-in firewall rules you have to do a factory reset `CMD> reset factory` and reconfigure Esperpass to connect to your local WiFi network.

**Comment by Dal78** [comment]
Confirmed i turned off the acl and immediately got hit.

Something is wrong with the ACL's.  Either missing protocols or IPs?  Can you sit and monitor the verbose deny log to see what is getting blocked?

**Comment by michaelshmitty** [comment]
@Dal78 Thanks for confirming this. I opened a separate issue #7 to work on this.
